/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/home.glb --transform --keepnames -o Home-transformed.jsx 
Files: public/home.glb [111.86MB] > /Users/philippe/home/home-transformed.glb [7.29MB] (93%)
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/home-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <pointLight name="Raum_Fill001" intensity={815.271} decay={2} position={[-1.5, 2, -0.331]} rotation={[-0.089, 0, 0]} />
      <pointLight name="Raum_Fill002" intensity={815.271} decay={2} position={[-1.5, 2, -3.071]} rotation={[-0.089, 0, 0]} />
      <pointLight name="Raum_Fill003" intensity={815.271} decay={2} position={[1.5, 2, -3.071]} rotation={[-0.089, 0, 0]} />
      <pointLight name="Point" intensity={135.879} decay={2} position={[0, 2.819, -3.3]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 0.5]} />
      <pointLight name="Raum_Fill" intensity={815.271} decay={2} position={[1.5, 2, -0.331]} rotation={[-0.089, 0, 0]} />
      <spotLight intensity={5435.141} angle={Math.PI / 2} penumbra={0.15} decay={2} color="#ffe7cc" position={[0, 2.872, -3.3]} rotation={[-Math.PI / 2, 0, 0]} target={nodes.Point002.target}>
        <primitive object={nodes.Point002.target} position={[0, 0, -1]} />
      </spotLight>
      <PerspectiveCamera name="Camera" makeDefault={false} far={100} near={0.05} fov={44.603} position={[0, 1.201, 2.593]} />
      <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials.LightmapBakeMat} position={[-1.75, -0.014, 2.733]} scale={[450, 75, 75]} />
      <mesh name="Raum" geometry={nodes.Raum.geometry} material={materials.Paper} position={[0, 1.75, 0]} />
      <mesh name="middleman" geometry={nodes.middleman.geometry} material={materials['Material.001']} position={[-3.179, 0.873, -3]} />
      <mesh name="mm-bretter" geometry={nodes['mm-bretter'].geometry} material={materials['MDF Board']} />
      <mesh name="ls-candle" geometry={nodes['ls-candle'].geometry} material={materials['10.6.2024_0']} position={[-3.15, 0.945, -2.661]} />
      <mesh name="alien_chair" geometry={nodes.alien_chair.geometry} material={materials.Material_0} position={[2.802, 0.611, -2.378]} rotation={[-Math.PI, 0.55, -Math.PI]} />
      <mesh name="x-bock_couch" geometry={nodes['x-bock_couch'].geometry} material={materials['Material_0.002']} position={[2.199, 0.183, -3.092]} rotation={[0, 0.782, 0]} />
      <mesh name="weblampe" geometry={nodes.weblampe.geometry} material={materials['Material_0.003']} />
      <mesh name="speaker_module" geometry={nodes.speaker_module.geometry} material={materials['Material_0.004']} position={[-2.65, -0.038, -4.528]} />
      <mesh name="glowing_puppe" geometry={nodes.glowing_puppe.geometry} material={materials['Material_0.005']} position={[-3.25, 1.435, -3.303]} />
      <mesh name="grillz_poster" geometry={nodes.grillz_poster.geometry} material={materials['Material.002']} position={[2.046, 1.573, -13.532]} scale={[1, 1, 0.5]} />
      <mesh name="Mesh_0001" geometry={nodes.Mesh_0001.geometry} material={materials['Material_0.007']} position={[-0.278, 0.613, -2.268]} rotation={[0, -1.218, 0]} />
      <mesh name="Regalbretter001" geometry={nodes.Regalbretter001.geometry} material={materials['Polished Oak Wood']} position={[-1.444, 1.3, -4.925]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh name="regal_(bild)" geometry={nodes['regal_(bild)'].geometry} material={materials.Material} position={[-1.442, 1.798, -4.98]} />
    </group>
  )
}

useGLTF.preload('/home-transformed.glb')
